### ISSUE TITLE
Call to openssl_cipher_iv_length()

### ISSUE THREAD

**Issue by AtefR** [star2000/laragon#1]
I tried to install php 7.2.27 and 7.4 to test with laragon it was installed successfully but when i try to run laravel application i get 

```
Symfony\Component\Debug\Exception\FatalThrowableError
Call to undefined function Illuminate\Encryption\openssl_cipher_iv_length()
```

the i have extension=openssl enabled on php.ini and i tried editing php\cli\conf.d\extensions.ini to have it but still the same error.

**Comment by star2000** [comment]
You may need to restart Nginx or Apache to make the configuration work.
